[project]
name = 'ExoplanetChain-Transit'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.astrobiology-research-rewards]
path = 'contracts/astrobiology-research-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.atmospheric-composition-analysis]
path = 'contracts/atmospheric-composition-analysis.clar'
clarity_version = 3
epoch = '3.2'

[contracts.habitability-zone-assessment]
path = 'contracts/habitability-zone-assessment.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stellar-variability-monitoring]
path = 'contracts/stellar-variability-monitoring.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
